"use client";
import React, { useState, useMemo, useEffect, useCallback } from "react";
import { useRouter } from "next/navigation";
import {
    AgentTable,
    AgentFormModal,
    WalletManagementModal,
    Agent,
} from "@/components/agents";
import Pagination from "@/components/ui/pagination/Pagination";
import { toast } from "sonner";
import { CustomDropdown, CompactDropdown } from "@/components/ui/dropdown/CustomDropdown";
import Spinner from "@/components/ui/spinner/Spinner";
import ActionConfirmationModal from "@/components/ui/modal/ActionConfirmationModal";
import EmptyState from "@/components/ui/empty-state/EmptyState";
import PlanGuard from "@/components/common/PlanGuard";

const ITEMS_PER_PAGE = 10;

export default function AgentsPage() {
    const router = useRouter();
    const [agents, setAgents] = useState<Agent[]>([]);
    const [loading, setLoading] = useState(true);
    const [searchQuery, setSearchQuery] = useState("");
    const [currentPage, setCurrentPage] = useState(1);
    const [totalItems, setTotalItems] = useState(0);

    // Modal states
    const [isFormModalOpen, setIsFormModalOpen] = useState(false);
    const [isWalletModalOpen, setIsWalletModalOpen] = useState(false);
    const [selectedAgent, setSelectedAgent] = useState<Agent | null>(null);
    const [isSaving, setIsSaving] = useState(false);

    // Delete Confirmation State
    const [pendingDelete, setPendingDelete] = useState<Agent | null>(null);

    // Fetch Agents from API
    const fetchAgents = useCallback(async () => {
        try {
            setLoading(true);
            const params = new URLSearchParams({
                page: currentPage.toString(),
                limit: ITEMS_PER_PAGE.toString(),
                search: searchQuery,
            });

            const res = await fetch(`/api/agents?${params.toString()}`);
            if (!res.ok) throw new Error('Failed to fetch agents');

            const result = await res.json();

            const mappedAgents = result.data.map((a: any) => ({
                id: a.id,
                fullName: a.fullName,
                email: a.email,
                phone: a.phone || "",
                icNumber: a.icNumber || "",
                ssmNumber: a.ssmNumber,
                bankName: a.bankName || "",
                bankAccountNumber: a.bankAccountNumber || "",
                bankAccountHolder: a.bankAccountHolder || "",
                agentCode: a.agentCode,
                commissionRate: Number(a.commissionRate),
                agentTier: a.agentTier,
                contractStatus: a.contractStatus,
                createdDate: a.createdAt,
                walletBalance: Number(a.walletBalance),
                avatar: a.avatarUrl || "/images/user/user-01.jpg",
            }));

            setAgents(mappedAgents);
            setTotalItems(result.pagination.total);
        } catch (error) {
            console.error("Failed to fetch agents", error);
            toast.error("Failed to load agents");
        } finally {
            setLoading(false);
        }
    }, [currentPage, searchQuery]);

    useEffect(() => {
        const timer = setTimeout(() => {
            fetchAgents();
        }, 300);
        return () => clearTimeout(timer);
    }, [fetchAgents]);

    const handleAddAgent = () => {
        setSelectedAgent(null);
        setIsFormModalOpen(true);
    };

    const handleView = (agent: Agent) => {
        router.push(`/agents/${agent.id}`);
    };

    const handleEdit = (agent: Agent) => {
        setSelectedAgent(agent);
        setIsFormModalOpen(true);
    };

    const handleDelete = (agent: Agent) => {
        setPendingDelete(agent);
    };

    const confirmDelete = async () => {
        if (pendingDelete) {
            try {
                const res = await fetch(`/api/agents/${pendingDelete.id}`, {
                    method: 'DELETE',
                });
                if (!res.ok) throw new Error('Failed to delete');

                toast.success("Agent deleted successfully");
                fetchAgents();
            } catch (error) {
                console.error(error);
                toast.error("Failed to delete agent");
            } finally {
                setPendingDelete(null);
            }
        }
    };

    const handleSaveAgent = async (agentData: Omit<Agent, "id" | "createdDate">) => {
        try {
            setIsSaving(true);

            // Prepare payload matching prisma schema (api/agents/route.ts)
            // Agent code is generated by backend for create, preserved for update
            const payload = {
                fullName: agentData.fullName,
                email: agentData.email,
                phone: agentData.phone,
                icNumber: agentData.icNumber,
                ssmNumber: agentData.ssmNumber,
                bankName: agentData.bankName,
                bankAccountNumber: agentData.bankAccountNumber,
                bankAccountHolder: agentData.bankAccountHolder,
                commissionRate: Number(agentData.commissionRate),
                agentTier: agentData.agentTier,
                contractStatus: agentData.contractStatus,
                // walletBalance is likely not manually editable here, handled via wallet modal
            };

            let res;
            if (selectedAgent) {
                // Update
                res = await fetch(`/api/agents/${selectedAgent.id}`, {
                    method: 'PUT',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(payload),
                });
            } else {
                // Create
                res = await fetch('/api/agents', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(payload),
                });
            }

            if (!res.ok) {
                const err = await res.json();
                throw new Error(err.error || 'Failed to save');
            }

            toast.success(selectedAgent ? "Agent updated successfully" : "Agent created successfully");
            setIsFormModalOpen(false);
            fetchAgents();
        } catch (error: any) {
            console.error("Error saving agent", error);
            toast.error(error.message);
        } finally {
            setIsSaving(false);
        }
    };

    const handleManageWallet = (agent: Agent) => {
        setSelectedAgent(agent);
        setIsWalletModalOpen(true);
    };

    const handleWalletSubmit = async (transaction: { type: 'credit' | 'debit'; amount: number; description: string }) => {
        if (!selectedAgent) return;

        try {
            const res = await fetch(`/api/agents/${selectedAgent.id}/wallet`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    type: transaction.type,
                    amount: transaction.amount,
                    description: transaction.description,
                    reference: transaction.description, // Use description as reference for now
                })
            });

            if (!res.ok) {
                const err = await res.json();
                throw new Error(err.error || 'Transaction failed');
            }

            toast.success(`${transaction.type === 'credit' ? 'Deposited' : 'Withdrawn'} RM${transaction.amount}`);
            setIsWalletModalOpen(false);
            fetchAgents(); // Refresh to update balance
        } catch (error: any) {
            console.error("Wallet transaction error", error);
            toast.error(error.message);
        }
    };

    const totalPages = Math.ceil(totalItems / ITEMS_PER_PAGE);

    return (
        <PlanGuard feature="agents">
            <div>
                {/* Page Header */}
                <div className="flex flex-col gap-4 mb-6 sm:flex-row sm:items-center sm:justify-between">
                    <div>
                        <h1 className="text-2xl font-semibold text-gray-800 dark:text-white">
                            Agents
                        </h1>
                        <p className="text-sm text-gray-500 dark:text-gray-400">
                            Manage your sales agents and their commissions
                        </p>
                    </div>
                    <nav>
                        <ol className="flex items-center gap-2 text-sm">
                            <li>
                                <a
                                    href="/"
                                    className="text-gray-500 hover:text-brand-500 dark:text-gray-400"
                                >
                                    Home
                                </a>
                            </li>
                            <li className="text-gray-400 dark:text-gray-500">/</li>
                            <li className="text-brand-500">Agents</li>
                        </ol>
                    </nav>
                </div>

                {/* Search and Actions */}
                <div className="flex flex-col gap-4 mb-6 sm:flex-row sm:items-center sm:justify-between">
                    {/* Search */}
                    <div className="relative max-w-md flex-1">
                        <input
                            type="text"
                            placeholder="Search agents..."
                            value={searchQuery}
                            onChange={(e) => {
                                setSearchQuery(e.target.value);
                                setCurrentPage(1);
                            }}
                            className="w-full h-11 pl-10 pr-4 text-sm border border-gray-300 rounded-lg bg-white focus:border-brand-300 focus:outline-hidden focus:ring-3 focus:ring-brand-500/10 dark:border-gray-700 dark:bg-gray-900 dark:text-white/90 dark:focus:border-brand-800"
                        />
                        <svg
                            className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"
                            width="20"
                            height="20"
                            viewBox="0 0 20 20"
                            fill="none"
                            xmlns="http://www.w3.org/2000/svg"
                        >
                            <path
                                d="M17.5 17.5L13.875 13.875M15.8333 9.16667C15.8333 12.8486 12.8486 15.8333 9.16667 15.8333C5.48477 15.8333 2.5 12.8486 2.5 9.16667C2.5 5.48477 5.48477 2.5 9.16667 2.5C12.8486 2.5 15.8333 5.48477 15.8333 9.16667Z"
                                stroke="currentColor"
                                strokeWidth="1.5"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                            />
                        </svg>
                    </div>

                    {/* Add Agent Button */}
                    <button
                        onClick={handleAddAgent}
                        className="inline-flex items-center gap-2 px-4 py-2.5 text-sm font-medium text-white bg-brand-500 rounded-lg hover:bg-brand-600 transition-colors shadow-theme-xs"
                    >
                        <svg
                            width="20"
                            height="20"
                            viewBox="0 0 20 20"
                            fill="none"
                            xmlns="http://www.w3.org/2000/svg"
                        >
                            <path
                                d="M10 4.16667V15.8333M4.16667 10H15.8333"
                                stroke="currentColor"
                                strokeWidth="1.5"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                            />
                        </svg>
                        Add Agent
                    </button>
                </div>

                {/* Agent Count */}
                {!loading && (
                    <div className="mb-4 text-sm text-gray-500 dark:text-gray-400">
                        {`Showing ${agents.length} of ${totalItems} agents`}
                    </div>
                )}

                {/* Agent Table */}
                {loading && agents.length === 0 ? (
                    <div className="flex justify-center items-center p-12">
                        <Spinner size="md" />
                    </div>
                ) : (
                    <AgentTable
                        agents={agents}
                        onView={handleView}
                        onEdit={handleEdit}
                        onDelete={handleDelete}
                        onManageWallet={handleManageWallet}
                    />
                )}

                {/* Pagination */}
                {totalPages > 1 && (
                    <div className="flex justify-center mt-6">
                        <Pagination
                            currentPage={currentPage}
                            totalPages={totalPages}
                            onPageChange={setCurrentPage}
                        />
                    </div>
                )}

                {/* Form Modal */}
                <AgentFormModal
                    isOpen={isFormModalOpen}
                    onClose={() => setIsFormModalOpen(false)}
                    onSave={handleSaveAgent}
                    agent={selectedAgent}
                    // @ts-ignore - Prop was added but interface might be cached in TS check
                    loading={isSaving}
                />

                {/* Wallet Management Modal */}
                <WalletManagementModal
                    isOpen={isWalletModalOpen}
                    onClose={() => setIsWalletModalOpen(false)}
                    agent={selectedAgent}
                    onSubmit={handleWalletSubmit}
                />

                <ActionConfirmationModal
                    isOpen={!!pendingDelete}
                    onClose={() => setPendingDelete(null)}
                    onConfirm={confirmDelete}
                    title="Delete Agent"
                    description={`Are you sure you want to delete ${pendingDelete?.fullName}? This action cannot be undone.`}
                    confirmText="Delete"
                    variant="danger"
                />
            </div>
        </PlanGuard>
    );
}
